name: Release tagged Commit

on:
  workflow_call:
  push:
    # branches: [ main ]  # this is handled as OR (push to main OR tagged)
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  pages: write  # TODO: probably not needed
  id-token: write # TODO: probably not needed

jobs:
  build-pages:
    permissions:
      pages: write
      id-token: write
    uses: sphinx_to_pages.yaml
  build-pdf:
    uses: sphinx_to_pdf.yaml
  release:
    runs-on: ubuntu-latest
    needs:
      - build-pages
      - build-pdf
    steps:

      - name: Download Artifact PDF
        uses: actions/download-artifact@v6
        # this will unpack zip, usable like below

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: Trampolinturnen/trampolinturnen.pdf
        if: startsWith(github.ref, 'refs/tags/')
